### ISSUE TITLE
HttpRequestException: Request was unsuccessful

### ISSUE THREAD

**Issue by Cori2018** [frankvHoof93/TikTokLiveSharp#13]
Yesterday I can start tiktok live, run just fine. but now I can't

here's the log:

HttpRequestException: Request was unsuccessful
TikTokLiveSharp.Client.HTTP.TikTokHttpRequest.GetContent () (at Assets/TikTokLiveSharp/TikTokLiveSharp/Client/HTTP/TikTokHttpRequest.cs:184)
TikTokLiveSharp.Client.HTTP.TikTokHttpRequest.Get () (at Assets/TikTokLiveSharp/TikTokLiveSharp/Client/HTTP/TikTokHttpRequest.cs:140)
TikTokLiveSharp.Client.HTTP.TikTokHTTPClient.GetRequest (System.String url, System.Collections.Generic.Dictionary`2[TKey,TValue] parameters, System.Boolean signURL) (at Assets/TikTokLiveSharp/TikTokLiveSharp/Client/HTTP/TikTokHTTPClient.cs:116)
TikTokLiveSharp.Client.HTTP.TikTokHTTPClient.GetDeserializedMessage (System.String path, System.Collections.Generic.Dictionary`2[TKey,TValue] parameters, System.Boolean signURL) (at Assets/TikTokLiveSharp/TikTokLiveSharp/Client/HTTP/TikTokHTTPClient.cs:64)
TikTokLiveSharp.Client.TikTokBaseClient.FetchClientData () (at Assets/TikTokLiveSharp/TikTokLiveSharp/Client/TikTokBaseClient.cs:527)
TikTokLiveSharp.Client.TikTokBaseClient.Connect (System.Action`1[T] onConnectException) (at Assets/TikTokLiveSharp/TikTokLiveSharp/Client/TikTokBaseClient.cs:349)
TikTokLiveSharp.Client.TikTokLiveClient.Connect (System.Action`1[T] onConnectException) (at Assets/TikTokLiveSharp/TikTokLiveSharp/Client/TikTokLiveClient.cs:266)
TikTokLiveSharp.Client.TikTokBaseClient.Start (System.Nullable`1[T] cancellationToken, System.Action`1[T] onConnectException, System.Boolean retryConnection) (at Assets/TikTokLiveSharp/TikTokLiveSharp/Client/TikTokBaseClient.cs:248)
UnityEngine.Debug:LogException(Exception, Object)
TikTokLiveSharp.Debugging.Debug:LogException(Exception, Object) (at Assets/TikTokLiveSharp/TikTokLiveSharp/Debugging/Debug.cs:84)
TikTokLiveSharp.Client.<Start>d__40:MoveNext() (at Assets/TikTokLiveSharp/TikTokLiveSharp/Client/TikTokBaseClient.cs:298)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetException(Exception)
TikTokLiveSharp.Client.<Connect>d__132:MoveNext() (at Assets/TikTokLiveSharp/TikTokLiveSharp/Client/TikTokLiveClient.cs:270)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetException(Exception)
TikTokLiveSharp.Client.<Connect>d__41:MoveNext() (at Assets/TikTokLiveSharp/TikTokLiveSharp/Client/TikTokBaseClient.cs:356)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetException(Exception)
TikTokLiveSharp.Client.<FetchClientData>d__47:MoveNext() (at Assets/TikTokLiveSharp/TikTokLiveSharp/Client/TikTokBaseClient.cs:530)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetException(Exception)
TikTokLiveSharp.Client.HTTP.<GetDeserializedMessage>d__4:MoveNext() (at Assets/TikTokLiveSharp/TikTokLiveSharp/Client/HTTP/TikTokHTTPClient.cs:65)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetException(Exception)
TikTokLiveSharp.Client.HTTP.<GetRequest>d__8:MoveNext() (at Assets/TikTokLiveSharp/TikTokLiveSharp/Client/HTTP/TikTokHTTPClient.cs:116)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetException(Exception)
TikTokLiveSharp.Client.HTTP.<Get>d__19:MoveNext() (at Assets/TikTokLiveSharp/TikTokLiveSharp/Client/HTTP/TikTokHttpRequest.cs:140)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetException(Exception)
TikTokLiveSharp.Client.HTTP.<GetContent>d__22:MoveNext() (at Assets/TikTokLiveSharp/TikTokLiveSharp/Client/HTTP/TikTokHttpRequest.cs:195)
UnityEngine.UnitySynchronizationContext:ExecuteTasks()

**Comment by danieltobon** [comment]
i have same problem

**Comment by isaackogan** [comment]
Issue fixed

**Comment by AbdurrahmanSefer** [comment]
how you fix it i have same problem 

One or more errors occurred. (Request was unsuccessful)

at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken) at System.Threading.Tasks.Task.Wait() at TikTokLiveSharp.Client.TikTokBaseClient.Run(Nullable`1 cancellationToken, Action`1 onConnectException, Boolean retryConnection) in G:\Visual_studio_projects\Anket\TikTokLiveSharp\Client\TikTokBaseClient.cs:line 226 at Anket2.Controllers.HomeController.d__7.MoveNext() in G:\Visual_studio_projects\Anket\Anket2\Anket2\Controllers\HomeController.cs:line 54
