### ISSUE TITLE
I can't access the  Top viewers list 

### ISSUE THREAD

**Issue by AbdurrahmanSefer** [frankvHoof93/TikTokLiveSharp#14]
Hello good day ; I used the library, it is very excellent, thank you, but I could not find the Top viewers list from anywhere, where and how can we use it

**Comment by AbdurrahmanSefer** [comment]
Thanks Yes that's right, I was using the library in NuGet Package so I can't see it, when will you update the library there?

**Comment by frankvHoof93** [comment]
New NuGet package now available via the ID TikTokLive_Sharp.
Since this fork is a breaking change (and since I do not have developer permissions for the original NuGet Package), this is a slight namechange from the original package by sebheron
