### ISSUE TITLE
Lib stop listening to comming likes/events

### ISSUE THREAD

**Issue by MrPatryk** [frankvHoof93/TikTokLiveSharp#15]
Hey, after 10-20minutes, sometimes after 1h game stops listening to new likes, gifts,joins etc -events. I try to disconnect and connect again but when lib website is down there are issues and can't connect till someone fixes domain :) how to avoid stopping listenings to events to dont regenerate tokens from your site which can be down = game useless for few hours till you react.

**Comment by kmarcin01** [comment]
same problem

**Comment by AbdurrahmanSefer** [comment]
same problem

**Comment by frankvHoof93** [comment]
Can any of you confirm what the state of the WebSocket is when it stops receiving events?
(TikTokLiveClient -> TikTokWebSocket -> ClientWebSocket -> State).

**Comment by danieltobon** [comment]
the state is aborted

**Comment by frankvHoof93** [comment]
Resolved in v0.9.5. 
Socket-loops will now check for socketstate, and will reconnect the SocketClient if the state is aborted.
