### ISSUE TITLE
'Request was unsuccessful' error occured.

### ISSUE THREAD

**Issue by BrightLight1115A** [frankvHoof93/TikTokLiveSharp#18]
Hello, have a wonderful day.
I am trying to implement Tiktok livestream function.
Here's a video I captured the attempt to receive events likes follow, likes, gift from live streaming the game.
Some errors occured when I press connect button.

Below is the video sharing link.
https://drive.google.com/file/d/1ObHaM7MjevvdGZzjzMwQ218ni7iqCI5n/view?usp=share_link

Please help me how to fix these erros.

**Comment by frankvHoof93** [comment]
When connecting, use the 'UniqueId' for the host.
That's the @-name, without the @.
In your video, that would be "myfriend.ryo"

**Comment by BrightLight1115A** [comment]
Thank you for your help.
I changed the host id to "myfriend.ryo" along your advice and it works well for a while.
But after restarting the Unity project, another error has caused and I couldn't fix it.
The video link is below.
https://drive.google.com/file/d/14bQwwDo2B9JRg-UBv66yAQVODrqUEo_y/view?usp=share_link
Excuse me, please fix this error.
