### ISSUE TITLE
[Your IP or country might be blocked by TikTok.]

### ISSUE THREAD

**Issue by Daviko290** [frankvHoof93/TikTokLiveSharp#22]
When I try to connect I get Your IP or country might be blocked by TikTok. why can this error be

**Comment by danieltobon** [comment]
Same problem

**Comment by fvz233** [comment]
same

**Comment by alxcalx** [comment]
uncheck enable compression within the TikTokLiveManager's client settings.

**Comment by HugoB07** [comment]
this error is when your computer try to fetch the room id, so skip room info don't fixe this problem
