### ISSUE TITLE
WebException timeout

### ISSUE THREAD

**Issue by Blurbss** [frankvHoof93/TikTokLiveSharp#24]
Setup the example project in unity and am trying to connect to multiple streams and getting timed out every time. Any ideas?

![image](https://github.com/frankvHoof93/TikTokLiveSharp/assets/104739499/afbb45ea-36a4-4084-ad34-0cadebebf15b)

**Comment by frankvHoof93** [comment]
Http-Requests are only sent during initial connect (to scrape the TikTokLive-Page for the required data (such as RoomId)).
If these are timing out, it sounds like you're unable to access the actual TikTokLiveStream-Page for the user?

**Comment by vashe96** [comment]
I receive same issue on all users and projects:

WebException: The operation has timed out.
System.Net.HttpWebRequest.RunWithTimeoutWorker[T] (System.Threading.Tasks.Task`1[TResult] workerTask, System.Int32 timeout, System.Action abort, System.Func`1[TResult] aborted, System.Threading.CancellationTokenSource cts) (at <b33672c2670a41d3b6cd2c30c98a2bed>:0)
System.Net.HttpWebRequest.EndGetResponse (System.IAsyncResult asyncResult) (at <b33672c2670a41d3b6cd2c30c98a2bed>:0)
System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) (at <d6232873609549b8a045fa15811a5bd3>:0)
--- End of stack trace from previous location where exception was thrown ---
System.Net.Http.MonoWebRequestHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) (at <d2e0c155f51449e5a9de344eb45213e1>:0)
Rethrow as HttpRequestException: An error occurred while sending the request
System.Net.Http.MonoWebRequestHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) (at <d2e0c155f51449e5a9de344eb45213e1>:0)
System.Net.Http.HttpClient.SendAsyncWorker (System.Net.Http.HttpRequestMessage request, System.Net.Http.HttpCompletionOption completionOption, System.Threading.CancellationToken cancellationToken) (at <d2e0c155f51449e5a9de344eb45213e1>:0)
TikTokLiveSharp.Client.HTTP.TikTokHttpRequest.GetContent () (at Library/PackageCache/dev.vanhoof.tiktokliveunity@235e10ef40/TikTokLiveSharp/Client/HTTP/TikTokHttpRequest.cs:180)
TikTokLiveSharp.Client.HTTP.TikTokHttpRequest.Get () (at Library/PackageCache/dev.vanhoof.tiktokliveunity@235e10ef40/TikTokLiveSharp/Client/HTTP/TikTokHttpRequest.cs:140)
TikTokLiveSharp.Client.HTTP.TikTokHTTPClient.GetSignedUrl (System.String url, System.Collections.Generic.Dictionary`2[TKey,TValue] parameters) (at Library/PackageCache/dev.vanhoof.tiktokliveunity@235e10ef40/TikTokLiveSharp/Client/HTTP/TikTokHTTPClient.cs:172)
TikTokLiveSharp.Client.HTTP.TikTokHTTPClient.GetRequest (System.String url, System.Collections.Generic.Dictionary`2[TKey,TValue] parameters, System.Boolean signURL) (at Library/PackageCache/dev.vanhoof.tiktokliveunity@235e10ef40/TikTokLiveSharp/Client/HTTP/TikTokHTTPClient.cs:126)
TikTokLiveSharp.Client.HTTP.TikTokHTTPClient.GetDeserializedMessage (System.String path, System.Collections.Generic.Dictionary`2[TKey,TValue] parameters, System.Boolean signURL) (at Library/PackageCache/dev.vanhoof.tiktokliveunity@235e10ef40/TikTokLiveSharp/Client/HTTP/TikTokHTTPClient.cs:64)
TikTokLiveSharp.Client.TikTokBaseClient.FetchClientData () (at Library/PackageCache/dev.vanhoof.tiktokliveunity@235e10ef40/TikTokLiveSharp/Client/TikTokBaseClient.cs:600)
TikTokLiveSharp.Client.TikTokBaseClient.Connect (System.Action`1[T] onConnectException) (at Library/PackageCache/dev.vanhoof.tiktokliveunity@235e10ef40/TikTokLiveSharp/Client/TikTokBaseClient.cs:418)
TikTokLiveSharp.Client.TikTokLiveClient.Connect (System.Action`1[T] onConnectException) (at Library/PackageCache/dev.vanhoof.tiktokliveunity@235e10ef40/TikTokLiveSharp/Client/TikTokLiveClient.cs:266)
TikTokLiveSharp.Client.TikTokBaseClient.Start (System.Nullable`1[T] cancellationToken, System.Action`1[T] onConnectException, System.Boolean retryConnection) (at Library/PackageCache/dev.vanhoof.tiktokliveunity@235e10ef40/TikTokLiveSharp/Client/TikTokBaseClient.cs:317)
UnityEngine.Debug:LogException(Exception, Object)
TikTokLiveSharp.Client.<Start>d__42:MoveNext() (at Library/PackageCache/dev.vanhoof.tiktokliveunity@235e10ef40/TikTokLiveSharp/Client/TikTokBaseClient.cs:367)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetException(Exception)
TikTokLiveSharp.Client.<Connect>d__132:MoveNext() (at Library/PackageCache/dev.vanhoof.tiktokliveunity@235e10ef40/TikTokLiveSharp/Client/TikTokLiveClient.cs:270)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetException(Exception)
TikTokLiveSharp.Client.<Connect>d__43:MoveNext() (at Library/PackageCache/dev.vanhoof.tiktokliveunity@235e10ef40/TikTokLiveSharp/Client/TikTokBaseClient.cs:425)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetException(Exception)
TikTokLiveSharp.Client.<FetchClientData>d__49:MoveNext() (at Library/PackageCache/dev.vanhoof.tiktokliveunity@235e10ef40/TikTokLiveSharp/Client/TikTokBaseClient.cs:603)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetException(Exception)
TikTokLiveSharp.Client.HTTP.<GetDeserializedMessage>d__4:MoveNext() (at Library/PackageCache/dev.vanhoof.tiktokliveunity@235e10ef40/TikTokLiveSharp/Client/HTTP/TikTokHTTPClient.cs:65)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetException(Exception)
TikTokLiveSharp.Client.HTTP.<GetRequest>d__9:MoveNext() (at Library/PackageCache/dev.vanhoof.tiktokliveunity@235e10ef40/TikTokLiveSharp/Client/HTTP/TikTokHTTPClient.cs:127)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetException(Exception)
TikTokLiveSharp.Client.HTTP.<GetSignedUrl>d__12:MoveNext() (at Library/PackageCache/dev.vanhoof.tiktokliveunity@235e10ef40/TikTokLiveSharp/Client/HTTP/TikTokHTTPClient.cs:185)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetException(Exception)
TikTokLiveSharp.Client.HTTP.<Get>d__19:MoveNext() (at Library/PackageCache/dev.vanhoof.tiktokliveunity@235e10ef40/TikTokLiveSharp/Client/HTTP/TikTokHttpRequest.cs:140)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetException(Exception)
TikTokLiveSharp.Client.HTTP.<GetContent>d__22:MoveNext() (at Library/PackageCache/dev.vanhoof.tiktokliveunity@235e10ef40/TikTokLiveSharp/Client/HTTP/TikTokHttpRequest.cs:197)
UnityEngine.UnitySynchronizationContext:ExecuteTasks()

**Comment by frankvHoof93** [comment]
>TikTokLiveSharp.Client.HTTP.TikTokHTTPClient.GetSignedUrl (System.String url
Signing server is down currently.
It's maintained by the owner of the Python-lib, so there's nothing I can do about that.

**Comment by vashe96** [comment]
Can you provide this lib repository to push the owner?

**Comment by frankvHoof93** [comment]
https://github.com/isaackogan/TikTokLive
Not currently online on Discord, so I'm not expecting an immediate response.

**Comment by vashe96** [comment]
Same issue occurs

**Comment by Blurbss** [comment]
The way I solved this was going directly into the library code and brute-force increasing the timeout limit. I took on average like a minute or two to connect for me, so it was giving up way too early. Hope that helps.

**Comment by vashe96** [comment]
> The way I solved this was going directly into the library code and brute-force increasing the timeout limit. It took on average like a minute or two to connect for me, so it was giving up way too early. Hope that helps.

Could you provide the solution please?

**Comment by Blurbss** [comment]
> > The way I solved this was going directly into the library code and brute-force increasing the timeout limit. It took on average like a minute or two to connect for me, so it was giving up way too early. Hope that helps.
> 
> Could you provide the solution please?

In Constants.cs
![image](https://github.com/frankvHoof93/TikTokLiveSharp/assets/104739499/95b62f9f-7645-4ec3-8c10-b367328e7fb9)

**Comment by vashe96** [comment]
Doesn't work, then I receive new error:

HttpRequestException: Request was unsuccessful [502]
TikTokLiveSharp.Client.HTTP.TikTokHttpRequest.GetContent () (at Library/PackageCache/dev.vanhoof.tiktokliveunity@235e10ef40/TikTokLiveSharp/Client/HTTP/TikTokHttpRequest.cs:186)
TikTokLiveSharp.Client.HTTP.TikTokHttpRequest.Get () (at Library/PackageCache/dev.vanhoof.tiktokliveunity@235e10ef40/TikTokLiveSharp/Client/HTTP/TikTokHttpRequest.cs:140)
TikTokLiveSharp.Client.HTTP.TikTokHTTPClient.GetSignedUrl (System.String url, System.Collections.Generic.Dictionary`2[TKey,TValue] parameters) (at Library/PackageCache/dev.vanhoof.tiktokliveunity@235e10ef40/TikTokLiveSharp/Client/HTTP/TikTokHTTPClient.cs:172)
TikTokLiveSharp.Client.HTTP.TikTokHTTPClient.GetRequest (System.String url, System.Collections.Generic.Dictionary`2[TKey,TValue] parameters, System.Boolean signURL) (at Library/PackageCache/dev.vanhoof.tiktokliveunity@235e10ef40/TikTokLiveSharp/Client/HTTP/TikTokHTTPClient.cs:126)
TikTokLiveSharp.Client.HTTP.TikTokHTTPClient.GetDeserializedMessage (System.String path, System.Collections.Generic.Dictionary`2[TKey,TValue] parameters, System.Boolean signURL) (at Library/PackageCache/dev.vanhoof.tiktokliveunity@235e10ef40/TikTokLiveSharp/Client/HTTP/TikTokHTTPClient.cs:64)
TikTokLiveSharp.Client.TikTokBaseClient.FetchClientData () (at Library/PackageCache/dev.vanhoof.tiktokliveunity@235e10ef40/TikTokLiveSharp/Client/TikTokBaseClient.cs:600)
TikTokLiveSharp.Client.TikTokBaseClient.Connect (System.Action`1[T] onConnectException) (at Library/PackageCache/dev.vanhoof.tiktokliveunity@235e10ef40/TikTokLiveSharp/Client/TikTokBaseClient.cs:418)
TikTokLiveSharp.Client.TikTokLiveClient.Connect (System.Action`1[T] onConnectException) (at Library/PackageCache/dev.vanhoof.tiktokliveunity@235e10ef40/TikTokLiveSharp/Client/TikTokLiveClient.cs:266)
TikTokLiveSharp.Client.TikTokBaseClient.Start (System.Nullable`1[T] cancellationToken, System.Action`1[T] onConnectException, System.Boolean retryConnection) (at Library/PackageCache/dev.vanhoof.tiktokliveunity@235e10ef40/TikTokLiveSharp/Client/TikTokBaseClient.cs:317)
UnityEngine.Debug:LogException(Exception, Object)
TikTokLiveSharp.Client.<Start>d__42:MoveNext() (at Library/PackageCache/dev.vanhoof.tiktokliveunity@235e10ef40/TikTokLiveSharp/Client/TikTokBaseClient.cs:367)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetException(Exception)
TikTokLiveSharp.Client.<Connect>d__132:MoveNext() (at Library/PackageCache/dev.vanhoof.tiktokliveunity@235e10ef40/TikTokLiveSharp/Client/TikTokLiveClient.cs:270)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetException(Exception)
TikTokLiveSharp.Client.<Connect>d__43:MoveNext() (at Library/PackageCache/dev.vanhoof.tiktokliveunity@235e10ef40/TikTokLiveSharp/Client/TikTokBaseClient.cs:425)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetException(Exception)
TikTokLiveSharp.Client.<FetchClientData>d__49:MoveNext() (at Library/PackageCache/dev.vanhoof.tiktokliveunity@235e10ef40/TikTokLiveSharp/Client/TikTokBaseClient.cs:603)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetException(Exception)
TikTokLiveSharp.Client.HTTP.<GetDeserializedMessage>d__4:MoveNext() (at Library/PackageCache/dev.vanhoof.tiktokliveunity@235e10ef40/TikTokLiveSharp/Client/HTTP/TikTokHTTPClient.cs:65)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetException(Exception)
TikTokLiveSharp.Client.HTTP.<GetRequest>d__9:MoveNext() (at Library/PackageCache/dev.vanhoof.tiktokliveunity@235e10ef40/TikTokLiveSharp/Client/HTTP/TikTokHTTPClient.cs:127)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetException(Exception)
TikTokLiveSharp.Client.HTTP.<GetSignedUrl>d__12:MoveNext() (at Library/PackageCache/dev.vanhoof.tiktokliveunity@235e10ef40/TikTokLiveSharp/Client/HTTP/TikTokHTTPClient.cs:185)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetException(Exception)
TikTokLiveSharp.Client.HTTP.<Get>d__19:MoveNext() (at Library/PackageCache/dev.vanhoof.tiktokliveunity@235e10ef40/TikTokLiveSharp/Client/HTTP/TikTokHttpRequest.cs:140)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetException(Exception)
TikTokLiveSharp.Client.HTTP.<GetContent>d__22:MoveNext() (at Library/PackageCache/dev.vanhoof.tiktokliveunity@235e10ef40/TikTokLiveSharp/Client/HTTP/TikTokHttpRequest.cs:197)
UnityEngine.UnitySynchronizationContext:ExecuteTasks()

**Comment by vashe96** [comment]
Should I try some kind of retry mechanism?
