### ISSUE TITLE
likes are doesn't working [BUG]

### ISSUE THREAD

**Issue by ugurberkecan** [frankvHoof93/TikTokLiveSharp#28]
**Describe the bug**
Likes are not showing in the screen and I can see only comments also some gifts are not working as well.

**Comment by yogev2255** [comment]
Tiktok has likes limit (around 4k) per user this is why you able to see it on the screen 
about the gifts I have the bug aswell if its the same gift with same animation something like that

**Comment by ugurberkecan** [comment]
I don't get it I don't see likes on the screen but I can see gifts and comments @yogev2255
