### ISSUE TITLE
[BUG]Lib won't detect comments

### ISSUE THREAD

**Issue by yogev2255** [frankvHoof93/TikTokLiveSharp#32]
**Describe the bug**
Hey,
For some reason, the library will ignore the comments of users and it won't send it as an event to Unity its just ignores them

**To Reproduce**
I am not sure but I just subscribed to the comment event and checked if the event is invoked but it's not 
and again it's not doing it for everyone some are working fine and some it won't detect it

**Comment by Nolifs** [comment]
seems to mainly happen if the message is a duplicate from the previous I figured out. At least for me

**Comment by frankvHoof93** [comment]
All comments that are sent by the server will invoke an event in the lib.
If the lib isn't invoking an event, that's because the server isn't sending a message for it.
This is likely because TikTok is considering your comment to be 'spam', and therefore not sending it to any (other) viewers.
