### ISSUE TITLE
[BUG] Ukrainian IP problem

### ISSUE THREAD

**Issue by vashe96** [frankvHoof93/TikTokLiveSharp#34]
I receive this message while connecting through ukrainian IP:

HttpRequestException: Request was unsuccessful [403]
TikTokLiveSharp.Client.HTTP.TikTokHttpRequest.GetContent () (at Library/PackageCache/dev.vanhoof.tiktokliveunity@235e10ef40/TikTokLiveSharp/Client/HTTP/TikTokHttpRequest.cs:186)
TikTokLiveSharp.Client.HTTP.TikTokHttpRequest.Get () (at Library/PackageCache/dev.vanhoof.tiktokliveunity@235e10ef40/TikTokLiveSharp/Client/HTTP/TikTokHttpRequest.cs:140)
TikTokLiveSharp.Client.HTTP.TikTokHTTPClient.GetSignedUrl (System.String url, System.Collections.Generic.Dictionary`2[TKey,TValue] parameters) (at Library/PackageCache/dev.vanhoof.tiktokliveunity@235e10ef40/TikTokLiveSharp/Client/HTTP/TikTokHTTPClient.cs:172)
TikTokLiveSharp.Client.HTTP.TikTokHTTPClient.GetRequest (System.String url, System.Collections.Generic.Dictionary`2[TKey,TValue] parameters, System.Boolean signURL) (at Library/PackageCache/dev.vanhoof.tiktokliveunity@235e10ef40/TikTokLiveSharp/Client/HTTP/TikTokHTTPClient.cs:126)
TikTokLiveSharp.Client.HTTP.TikTokHTTPClient.GetDeserializedMessage (System.String path, System.Collections.Generic.Dictionary`2[TKey,TValue] parameters, System.Boolean signURL) (at Library/PackageCache/dev.vanhoof.tiktokliveunity@235e10ef40/TikTokLiveSharp/Client/HTTP/TikTokHTTPClient.cs:64)
TikTokLiveSharp.Client.TikTokBaseClient.FetchClientData () (at Library/PackageCache/dev.vanhoof.tiktokliveunity@235e10ef40/TikTokLiveSharp/Client/TikTokBaseClient.cs:600)
TikTokLiveSharp.Client.TikTokBaseClient.Connect (System.Action`1[T] onConnectException) (at Library/PackageCache/dev.vanhoof.tiktokliveunity@235e10ef40/TikTokLiveSharp/Client/TikTokBaseClient.cs:418)
TikTokLiveSharp.Client.TikTokLiveClient.Connect (System.Action`1[T] onConnectException) (at Library/PackageCache/dev.vanhoof.tiktokliveunity@235e10ef40/TikTokLiveSharp/Client/TikTokLiveClient.cs:266)
TikTokLiveSharp.Client.TikTokBaseClient.Start (System.Nullable`1[T] cancellationToken, System.Action`1[T] onConnectException, System.Boolean retryConnection) (at Library/PackageCache/dev.vanhoof.tiktokliveunity@235e10ef40/TikTokLiveSharp/Client/TikTokBaseClient.cs:369)
TikTokLiveUnity.TikTokLiveManager.ConnectToStream (System.String userID, System.Action`1[T] onConnectException) (at Library/PackageCache/dev.vanhoof.tiktokliveunity@235e10ef40/TikTokLiveUnity/Runtime/TikTokLiveManager.cs:458)
UnityEngine.Debug:LogException(Exception, Object)
TikTokLiveUnity.<ConnectToStream>d__201:MoveNext() (at Library/PackageCache/dev.vanhoof.tiktokliveunity@235e10ef40/TikTokLiveUnity/Runtime/TikTokLiveManager.cs:465)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetException(Exception)
TikTokLiveSharp.Client.<Start>d__42:MoveNext() (at Library/PackageCache/dev.vanhoof.tiktokliveunity@235e10ef40/TikTokLiveSharp/Client/TikTokBaseClient.cs:355)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetException(Exception)
TikTokLiveSharp.Client.<Connect>d__132:MoveNext() (at Library/PackageCache/dev.vanhoof.tiktokliveunity@235e10ef40/TikTokLiveSharp/Client/TikTokLiveClient.cs:270)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetException(Exception)
TikTokLiveSharp.Client.<Connect>d__43:MoveNext() (at Library/PackageCache/dev.vanhoof.tiktokliveunity@235e10ef40/TikTokLiveSharp/Client/TikTokBaseClient.cs:425)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetException(Exception)
TikTokLiveSharp.Client.<FetchClientData>d__49:MoveNext() (at Library/PackageCache/dev.vanhoof.tiktokliveunity@235e10ef40/TikTokLiveSharp/Client/TikTokBaseClient.cs:603)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetException(Exception)
TikTokLiveSharp.Client.HTTP.<GetDeserializedMessage>d__4:MoveNext() (at Library/PackageCache/dev.vanhoof.tiktokliveunity@235e10ef40/TikTokLiveSharp/Client/HTTP/TikTokHTTPClient.cs:65)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetException(Exception)
TikTokLiveSharp.Client.HTTP.<GetRequest>d__9:MoveNext() (at Library/PackageCache/dev.vanhoof.tiktokliveunity@235e10ef40/TikTokLiveSharp/Client/HTTP/TikTokHTTPClient.cs:127)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetException(Exception)
TikTokLiveSharp.Client.HTTP.<GetSignedUrl>d__12:MoveNext() (at Library/PackageCache/dev.vanhoof.tiktokliveunity@235e10ef40/TikTokLiveSharp/Client/HTTP/TikTokHTTPClient.cs:185)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetException(Exception)
TikTokLiveSharp.Client.HTTP.<Get>d__19:MoveNext() (at Library/PackageCache/dev.vanhoof.tiktokliveunity@235e10ef40/TikTokLiveSharp/Client/HTTP/TikTokHttpRequest.cs:140)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetException(Exception)
TikTokLiveSharp.Client.HTTP.<GetContent>d__22:MoveNext() (at Library/PackageCache/dev.vanhoof.tiktokliveunity@235e10ef40/TikTokLiveSharp/Client/HTTP/TikTokHttpRequest.cs:197)
UnityEngine.UnitySynchronizationContext:ExecuteTasks()

While using VPN, all is good

**Comment by vashe96** [comment]
Now problem occurs even while using VPN

**Comment by frankvHoof93** [comment]
This is related to the signing-server, which I unfortunately do not have any control over.
V1.0.0 should have a better implementation of proxying, so you could try that.

If that does not work, try messaging in the general section of the Discord (the same signing-server is used for all TikTokLive-libraries).
