### ISSUE TITLE
Exception thrown: 'ProtoBuf.ProtoException' in protobuf-net.dll

### ISSUE THREAD

**Issue by RACEVOLUTION** [frankvHoof93/TikTokLiveSharp#4]
I get the following error message every now and then.
In TikTok Lives, where there is a lot of activity, already after a few seconds/minutes. 

Exception thrown: 'ProtoBuf.ProtoException' in protobuf-net.dll
'TikTok Agent.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App\6.0.15\System.Reflection.Metadata.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'TikTok Agent.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App\6.0.15\System.Collections.Immutable.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Exception thrown: 'TikTokLiveSharp.Errors.Messaging.WebcastMessageException' in TikTokLiveSharp.dll
Exception thrown: 'System.Net.WebSockets.WebSocketException' in TikTokLiveSharp.dll
Exception thrown: 'System.Net.WebSockets.WebSocketException' in System.Private.CoreLib.dll

**Comment by frankvHoof93** [comment]
Closed for inactivity.
If you find any proto-exception, please create a new issue with the Base64-data for the message.
