### ISSUE TITLE
[QUESTION] Does anyone has reconnect mechanism?

### ISSUE THREAD

**Issue by vashe96** [frankvHoof93/TikTokLiveSharp#40]
Does anyone has reconnect mechanism? While game get disconnected by any reason do we have mechanism to automatically renew connection?

**Comment by frankvHoof93** [comment]
There is no "Full Reconnect System" (as this could fall into an infinite loop).
There are Events for OnDisconnected & OnException that you could hook into to handle this in your own client (based on how & why it disconnected).
