### ISSUE TITLE
[BUG] Request was unsuccessful [403]

### ISSUE THREAD

**Issue by mubgit** [frankvHoof93/TikTokLiveSharp#41]
**Describe the bug**

**To Reproduce**

**Expected behavior**
Request was unsuccessful [403] We get this errror, even with vpn.. not works

**Base64 Message**
If your bug logged an error containing a message, please post the Base64-string here.

**Additional context**

**Comment by frankvHoof93** [comment]
Signing-Server error. Should be resolved.
