### ISSUE TITLE
[BUG] GiftMessage Duplication

### ISSUE THREAD

**Issue by HugoB07** [frankvHoof93/TikTokLiveSharp#58]
**Describe the bug**
When someone sent a gift, a few second after a can see another call of GiftMessage Function

![image](https://github.com/frankvHoof93/TikTokLiveSharp/assets/78440460/876304a0-8a04-4a3a-8a0c-c9252bdcf72d)

**To Reproduce**
1. Start the app
2. Connect to an user
3. Sent a gift (Rose etc)
4. Look the Console and see the duplication

**Comment by Daviko290** [comment]
I have this problem and I don't know how to solve it, did you manage to fix it?

**Comment by HugoB07** [comment]
https://github.com/frankvHoof93/TikTokLiveSharp/issues/11

check this issue
