### ISSUE TITLE
[BUG]Gift.Sender & GiftMessage.User

### ISSUE THREAD

**Issue by qrq** [frankvHoof93/TikTokLiveSharp#60]
**Describe the bug**
OnGift Event preset [Sender ]as TikTokGift Sender 

and in GiftMessage Event it preset [User] as a Gift Sender 

and all of it point to same person !!

**To Reproduce**

**Expected behavior**

**Base64 Message**
If your bug logged an error containing a message, please post the Base64-string here.

**Additional context**

**Comment by frankvHoof93** [comment]
Yes. These point to the person who sent the gift.
The receiver will usually be blank (indicating that the host received the gift).
