### ISSUE TITLE
isPendingStreak(data) C#

### ISSUE THREAD

**Issue by zandotc1** [frankvHoof93/TikTokLiveSharp#61]
How to use pending (isPendingStreak(data) similar to nodejs? to prevent the gift totalizer from calculating the previous accumulated quantity (+)current quantity.

Nodejs:
 <span>Repeat: <b style="${isPendingStreak(data) ? 'color:red' : ''}">x${data.repeatCount.toLocaleString()}</b><span><br>
                                <span>Cost: <b>${(data.diamondCount * data.repeatCount).toLocaleString()} Diamonds</b><span>

**Comment by HugoB07** [comment]
hello, I think you talk about the e.StreakEnd ?

**Comment by zandotc1** [comment]
Console:
rokamarker12, Gift:  Rose(1), ID: 5655
rokamarker12, Gift:  Rose(2), ID: 5655
rokamarker12, Gift:  Rose(3), ID: 5655

but:
rokamarket12 Sent  x3 Rose!

**Comment by zandotc1** [comment]
Like this?

if (e.StreakEnd)
                        {
                            function();
                        }
                        else { 
                        anhother function();
                        }

**Comment by HugoB07** [comment]
https://github.com/frankvHoof93/TikTokLiveSharp/issues/11

check this issue
