### ISSUE TITLE
Get Avatar (Profile Picture)[QUESTION]

### ISSUE THREAD

**Issue by zandotc1** [frankvHoof93/TikTokLiveSharp#62]
How to get avatar url?

 public void Client_OnComment(FormPrincipal form, TikTokLiveClient sender, Chat e)
        {
string commentText = $"{e.Sender.UniqueId}: {e.Message}";

//e.Sender.AvatarLarge;
//e.Sender.AvatarMedium;
//e.Sender.AvatarThumbnail

//e.User.AvatarLarge;
//e.User.AvatarMedium;
//e.User.AvatarThumbnail

 string avatarUri = e.Sender.AvatarThumbnail?.ToString() ?? "";
                    textBox3.Text = avatarUri;
 }

**Comment by HugoB07** [comment]
hello, you can do like that : e.Sender.AvatarThumbnail.Urls[0]}

Urls is a List of string

**Comment by zandotc1** [comment]
@HugoB07 You are the best. Thank you very much!
