### ISSUE TITLE
Accumulated likes

### ISSUE THREAD

**Issue by zandotc1** [frankvHoof93/TikTokLiveSharp#63]
By pressing "TAP TAP" several times, the like bar fills up, but when it explodes, it only counts 01 like. Is there a way to get the total number of likes, equal to the number sent in the likes bar?

Like imagem(83 likes), but in console count one...

![Imagem do WhatsApp de 2024-01-02 à(s) 18 53 49_a58b1d42](https://github.com/frankvHoof93/TikTokLiveSharp/assets/67649379/44c44652-6d85-4d95-8657-b74a46598a7d)

 private static void Client_OnLike(TikTokLiveClient sender, Like e)
        {
        
            Console.WriteLine($"{e.Sender.UniqueId} liked!"); // 01 but I sent 83 likes
        
        }

**Comment by HugoB07** [comment]
hello, e.Count (15 max per call) or e.Total (total like of the stream)

**Comment by zandotc1** [comment]
Ok @HugoB07, thx.... ^^
