### ISSUE TITLE
Combo gifts are counted as a single.

### ISSUE THREAD

**Issue by TimurSarp** [frankvHoof93/TikTokLiveSharp#68]
Just simple.

Combo gifts are counted as a single gift.

Example:
I can not see how much rose he gave me.

**Comment by frankvHoof93** [comment]
OnGift uses internal Events on the TikTokGift-Object which fire when the streak continues (or ends).
OnGiftMessage is fired for each message.

Having tested, I can assure you both are working as intended. 
Have a look at the summaries on both Events (and the TikTokGift-Class) for more info.
