### ISSUE TITLE
Hello, I want to adapt it to be deployed on a server for multiple clients. Is there any good way?

### ISSUE THREAD

**Issue by asdfg314284230** [frankvHoof93/TikTokLiveSharp#7]
Hello, I want to adapt it to be deployed on a server for multiple clients. Is there any good way?

**Comment by frankvHoof93** [comment]
You should be able to wrap TikTokLiveSharp in a .NET REST-API and run it like that.
It'll take some work though. And you'll want to use .NET CORE (not Framework) as a back-end, since the protobuf-library seems to have some issues on a .NET Framework backend.

**Comment by frankvHoof93** [comment]
Closed for inactivity
