### ISSUE TITLE
Do I need to obtain an API key? I'm getting a 429 error with GetSignedWebsocketData.

### ISSUE THREAD

**Issue by congwenchao0525** [frankvHoof93/TikTokLiveSharp#93]
I am a new developer and I was initially able to use this project, but later I received a "Signing Rate Limit Reached" message. While tracing the source code, I found that there is an `apiKey` parameter in `GetSignedWebsocketData`. I'm not sure if this parameter is required. If it is, how can I obtain it? Please help me with this, thank you all.

**Comment by isaackogan** [comment]
was a temporary issue and is now fixed
